#!/usr/bin/env python3
# openvpn-u2f-setup/openvpn-u2f-ask-password -- send U2F auth to OpenVPN server
# Copyright (C) 2021, Walter Doekes, OSSO B.V.
#
# This file is part of openvpn-u2f-setup. It is free software: you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, version 3
# or any later version.
#
# For documentation, sources and the full license, go to:
# https://github.com/ossobv/openvpn-u2f-setup
#
# This script needs to be installed as a daemon on your system so it
# can handle OpenVPN password requests through SystemD. Use the provided
# openvpn-u2f-ask-password.service file.

import json
import os
import signal
import subprocess
import sys
import traceback
import time
from base64 import urlsafe_b64encode
from warnings import warn

import pyinotify  # python3-pyinotify

try:
    import gi  # python3-gi (GObject for GTK+/GNOME)

    # "ValueError: Namespace Notify not available for version 0.8"
    gi.require_version('Notify', '0.7')  # hide version warning

    from gi.repository import Notify as GObjectNotify, GLib

    # You must do this before connecting to the bus. Otherwise we get no
    # asynchronous signal receptions.
    from dbus.mainloop.glib import DBusGMainLoop
    DBusGMainLoop(set_as_default=True)

    # We expect python3-dbus through these dependent apt packages:
    #   ubuntu-server -> software-properties-common -> python3-dbus
    import dbus
    dbus_session = dbus.SessionBus()
    dbus_system = dbus.SystemBus()
except ImportError as e:
    warn(
        'Could not load some or all requirements needed for GUI '
        'notification support: {}'.format(e))
    GObjectNotify = None
    dbus_session = None


# This must be the same on both sides for each new challenge. It's
# prefixed with "pam://" because the u2f-server is picky.
ORIGIN = 'pam://openvpn-server'
# This must be the same for the lifetime of the key handle
# (registration). If the appId is different, the u2host application
# refuses to sign (-6, authenticator error).
APPID = 'openvpn'


def is_in_screensaver():
    """
    Return True if the user screen is locked at the moment

    Use this to avoid waking up a blanked screen when away.
    """
    if dbus_session is None:
        return False  # we don't know

    screensaver_names = [
        'org.gnome.ScreenSaver',
        'org.cinnamon.ScreenSaver',
        'org.kde.screensaver',
        'org.freedesktop.ScreenSaver',
    ]
    for obj_name in screensaver_names:
        try:
            obj_path = '/{0}'.format(obj_name.replace('.', '/'))
            get_object = dbus_session.get_object(obj_name, obj_path)
            get_interface = dbus.Interface(get_object, obj_name)
            # >>> get_interface.proxy_object._introspect_method_map
            # {'org.freedesktop.DBus.Properties.Get': 'ss',
            #  'org.freedesktop.DBus.Properties.GetAll': 's',
            #  'org.freedesktop.DBus.Properties.Set': 'ssv',
            #  'org.freedesktop.DBus.Introspectable.Introspect': '',
            #  'org.freedesktop.DBus.Peer.Ping': '',
            #  'org.freedesktop.DBus.Peer.GetMachineId': '',
            #  'org.gnome.ScreenSaver.Lock': '',
            #  'org.gnome.ScreenSaver.GetActive': '',
            #  'org.gnome.ScreenSaver.SetActive': 'b',
            #  'org.gnome.ScreenSaver.GetActiveTime': ''}
            status = bool(get_interface.GetActive())
            break
        except dbus.exceptions.DBusException:
            pass
    else:
        warn('No applicable screensaver found')
        return False  # we don't know

    return status


def listen_for_unlock(handler):
    """
    Add the handler to known screensaver unlock signals.
    """
    if dbus_system is None:
        return

    # gdbus monitor --system -d org.freedesktop.login1
    # dbus-monitor --system \
    #   "type=signal,interface=org.freedesktop.login1.Session,member=Unlock"
    def safe_handler(*args, **kwargs):
        try:
            handler(*args, **kwargs)
        except Exception as e:
            traceback.print_exc()
            print('ERROR: safe_handler:', e)

    ret = dbus_system.add_signal_receiver(
        safe_handler,
        'Unlock',
        'org.freedesktop.login1.Session')
    print('DEBUG: listen_for', ret)
    assert ret, ret


class Notification:
    """
    GNOME notification class with stdout fallback.

    Used to notify GUI users that action needs to be taken.
    """
    @classmethod
    def init(cls):
        if not hasattr(cls, '_init'):
            cls._init = GObjectNotify.init(os.path.basename(sys.argv[0]))
            # Unused for now. Contains: [
            #   'actions', 'body', 'body-markup', 'icon-static', 'persistence',
            #   'sound']
            cls._caps = GObjectNotify.get_server_caps()

            for image_candidate in (
                    # gnome-icon-theme
                    '/usr/share/icons/gnome/48x48/devices/network-vpn.png',
                    # suru-icon-theme
                    '/usr/share/icons/suru/status/scalable/network-secure.svg',
                    # ubuntu-mono
                    ('/usr/share/icons/ubuntu-mono-dark/status/24/'
                     'nm-vpn-standalone-lock.svg'),
                    ):
                if os.path.isfile(image_candidate):
                    cls._image_path = image_candidate
                    break
            else:
                cls._image_path = 'dialog-warn'  # dialog-(information|error)

    def __init__(self, title, body, icon, autoclose=True):
        self._title = title
        self._body = body
        self._notification = None

        if GObjectNotify:
            self.init()
            self._notification = GObjectNotify.Notification.new(
                self._title, self._body, icon or self._image_path)
            self.set_autoclose(autoclose)

        self.show()

    def set_autoclose(self, autoclose):
        if self._notification:
            # On GNOME, the timeout is ignored. However, it we set urgency to
            # high, it is kept visible until manually dismissed.
            if autoclose:
                self._notification.set_urgency(1)   # 0=low, 1=normal, 2=high
                self._notification.set_timeout(-1)  # ignored
            else:
                self._notification.set_urgency(2)   # 0=low, 1=normal, 2=high
                self._notification.set_timeout(4)   # ignored

    def update(self, body, autoclose=True):
        self._body = body
        if self._notification:
            self._notification.set_property('body', self._body)
            self.set_autoclose(autoclose)

        self.show()

    def show(self):
        if self._notification:
            try:
                self._notification.show()
            except GLib.Error as e:
                # (Observed during boot.)
                # gi.repository.GLib.Error: g-dbus-error-quark:
                #   GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:
                #   The name :1.41 was not provided by any .service files (2)
                print('ERROR showing notification: {}'.format(e))

        print('> [{}]\n> {}'.format(self._title, self._body))


class Process:
    """
    Process helper; reads interesting stuff from /proc/PID.

    Used to detect which (openvpn) process is requesting a password.
    """
    @staticmethod
    def getppid(pid):
        try:
            with open('/proc/{}/stat'.format(pid), 'rb') as fp:
                stat = fp.read().decode('ascii', 'replace').split(' ')
        except OSError:  # FileNotFoundError? PermissionDenied?
            return 1
        # pid (comm) state ppid pgrp ... (see: man 5 proc)
        for i in range(1, len(stat)):
            if stat[i].endswith(')'):
                break
        else:
            return 1
        # i is now 1 except when there is a space in comm
        return int(stat[i + 2])

    @staticmethod
    def getcwd(pid):
        try:
            return os.readlink('/proc/{}/cwd'.format(pid))
        except OSError:  # FileNotFoundError? PermissionDenied?
            return ''

    @classmethod
    def getexe(cls, pid):
        try:
            return os.readlink('/proc/{}/exe'.format(pid))
        except OSError:  # FileNotFoundError? PermissionDenied?
            try:
                return cls.getcmdline(pid)[0]
            except IndexError:
                return ''

    @staticmethod
    def getcmdline(pid):
        try:
            with open('/proc/{}/cmdline'.format(pid), 'rb') as fp:
                return fp.read().decode('ascii', 'replace').split('\0')
        except OSError:  # FileNotFoundError? PermissionDenied?
            return []

    @classmethod
    def from_pid(cls, pid):
        try:
            os.kill(pid, 0)
        except OSError as e:
            if e.args[0] == 3:  # ESRCH [Errno 3] No such process
                print('pid {} is gone at {}'.format(pid, e))
                return None
            elif e.args[0] == 1:  # ENOPERM
                pass
        return cls(pid)

    def __init__(self, pid):
        self.pid = pid
        self.exe = self.getexe(pid)

        # Is the password request made through systemd-ask-password,
        # then fetch the parent process.
        # > /bin/systemd-ask-password --echo --icon network-vpn "Enter ...:"
        if self.exe.endswith('/systemd-ask-password'):
            ppid = self.getppid(pid)
            if ppid != 1:
                pid = ppid
                self.pid = pid
                self.exe = self.getexe(pid)

    @property
    def cwd(self):
        return self.getcwd(self.pid)

    @property
    def cmdline(self):
        return self.getcmdline(self.pid)

    def __repr__(self):
        return '<Process({}, {}>'.format(self.pid, self.exe)


class AskPassword:
    """
    Base AskPassword class, reusable if we wanted.

    Subclasses need to implement handle().
    """
    class CannotHandle(Exception):
        pass

    class TimeoutDuringHandling(Exception):
        pass

    def __init__(self, process):
        self.last_activity = time.time()
        self._process = process

    def make_request(self, askfilename, header, values):
        self._askfilename = askfilename
        self._header = header
        self._values = values
        self._not_after = int(self._values.get('NotAfter', 0)) / 1000000.0

    def is_valid(self):
        # print('DEBUG: isfile {} AND {} > {}'.format(
        #     os.path.isfile(self._askfilename), self._not_after,
        #     time.clock_gettime(time.CLOCK_MONOTONIC)))
        return (
            os.path.isfile(self._askfilename) and
            (not self._not_after
                or self._not_after > time.clock_gettime(time.CLOCK_MONOTONIC)))

    def respond(self, response):
        subprocess.run(
            ['/usr/bin/pkexec', '/lib/systemd/systemd-reply-password',
             '1', self._values['Socket']],
            input=response.encode('ascii'))
        print('DEBUG: response to {!r}: {}'.format(
            self._values.get('Message'),
            (response if len(response) <= 16
             else '{}...'.format(response[0:16]))))

    def handle(self):
        self.last_activity = time.time()
        raise NotImplementedError()


class AskPasswordOpenVpnU2f(AskPassword):
    """
    OpenVpnU2f specific AskPassword class.

    Called for usernames and passwords. Responds with keyhandle and
    (when U2F device is touched) with signed response.
    """
    @staticmethod
    def _get_config_filename_from_openvpn_process(process):
        cmdline = process.cmdline
        config = None
        try:
            idx = cmdline.index('--config')
            config = cmdline[idx + 1]
        except (IndexError, ValueError):
            # > If --config file is the only option to the openvpn
            # > command, the --config can be removed, and the command can
            # > be given as openvpn file
            if len(cmdline) == 2:
                config = cmdline[1]
        if config and config[0] != '/':
            # Find keyhandle in /etc/openvpn/{client/,}.
            for possible_path in (
                    process.cwd, '/etc/openvpn/client', '/etc/openvpn'):
                if os.path.isfile(os.path.join(possible_path, config)):
                    config = os.path.join(possible_path, config)
                    break
        assert os.path.isfile(config), config
        return config

    @staticmethod
    def _get_u2f_keyhandles_from_openvpn_config(config):
        """
        Assume config is .../<VPN>.conf and .../<VPN>/keyhandle.dat exists.
        """
        possible_cfg = [os.path.expanduser('~/.u2f_keys')]
        if config and config.endswith('.conf'):
            possible_cfg.append(
                os.path.join(config[0:-5], 'keyhandle.dat'))

        for cfg in possible_cfg:
            try:
                with open(cfg, 'r') as f:
                    print('DEBUG: using keyhandles from', cfg)
                    return [i.split()[0] for i in f.readlines() if i.split()]
            except IOError:
                pass
        else:
            raise ValueError(
                f'Cannot find U2F keyhandles: {possible_cfg!r}')

    @staticmethod
    def _make_challenge_request(keyhandle):
        # Make it an exact int and no padding of other stuff.
        # Must be 32 bytes in total, so we pad before challenging.
        timestamp = str(int(time.time()))
        assert len(timestamp) == 10, timestamp
        assert all(i in '0123456789' for i in timestamp), timestamp
        b64challenge = (
            urlsafe_b64encode(
                (timestamp + 'Z' + timestamp + 'Z' + timestamp)
                .encode('ascii'))
            .decode('ascii').replace('=', ''))

        # Create request to pass to u2f-host. Pretend we got this from
        # u2f-server -a authenticate.
        request = (
            f'{{"keyHandle": "{keyhandle}", "version": "U2F_V2", '
            f'"challenge": "{b64challenge}", "appId": "{APPID}"}}')
        return timestamp, request

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._password_response = None

    def _is_username_request(self):
        lower = self._values.get('Message').strip().lower().rstrip(':')
        return lower == 'enter auth username'  # 'Enter Auth Username:'

    def _is_password_request(self):
        lower = self._values.get('Message').strip().lower().rstrip(':')
        return lower == 'enter auth password'  # 'Enter Auth Password:'

    def handle(self):
        if is_in_screensaver():
            warn('Ignoring ask-password request because in screensaver mode')
            return

        try:
            if self._is_username_request():
                if self._password_response:
                    print('WARNING? Stale password? {}'.format(
                        self._password_response))
                    self._password_response = None

                self._handle_username_request()

            elif self._is_password_request():
                if not self._password_response:
                    print('WARNING. Skipped auth bit? Do nothing..')
                    return

                self._handle_password_request()

            else:
                assert False, 'Unexpected request: {}'.format(self._values)

        except (AskPassword.CannotHandle, AskPassword.TimeoutDuringHandling):
            pass

        else:
            # Update so it doesn't get pruned just yet.
            self.last_activity = time.time()

    def _handle_username_request(self):
        vpn_name, keyhandles = self._prepare_keypress_request()

        # Call upon work from the U2F token. This may take a while.
        keyhandle, timestamp, response = self._make_challenge_response(
            vpn_name, keyhandles)

        # Store timestamp+response for reuse when the password is
        # requested.
        self._password_response = '{}/{}'.format(timestamp, response)

        self.respond(keyhandle)

    def _handle_password_request(self):
        assert self._password_response, (
            self._process, self._password_response)
        # TODO/FIXME: assert that this is still the same openvpn?
        self.respond(self._password_response)
        self._password_response = None

    def _prepare_keypress_request(self):
        try:
            config = self._get_config_filename_from_openvpn_process(
                self._process)
        except AssertionError:  # FIXME: should not use assertionerror
            Notification(
                'OpenVPN config filename not found',
                ('openvpn-u2f-ask-password needs the config to find '
                 'the path to the keyhandle. Ignoring this auth request.'),
                self._values.get('Icon'))
            raise AskPassword.CannotHandle()

        vpn_name = os.path.basename(config).rsplit('.', 1)[0]
        try:
            keyhandles = self._get_u2f_keyhandles_from_openvpn_config(config)
        except FileNotFoundError:
            Notification(
                'OpenVPN {} has no U2F key handle'.format(vpn_name),
                ('No keyhandle.dat found. Assuming authentication is '
                 'handled elsewhere.'),
                self._values.get('Icon'))
            raise AskPassword.CannotHandle()
        except PermissionError:
            Notification(
                'OpenVPN {} could not read U2F key handle'.format(vpn_name),
                'Did you set the correct permissions? Ignoring this request.',
                self._values.get('Icon'))
            raise AskPassword.CannotHandle()

        return vpn_name, keyhandles

    def _make_challenge_response(self, vpn_name, keyhandles):
        # Do global (GUI?) notification.
        note = Notification(
            'OpenVPN {} U2F key request'.format(vpn_name),
            ('Please insert your hardware token for extra authentication. '
             'When it blinks, touch the button.'),
            self._values.get('Icon'), autoclose=False)

        t0 = time.time()
        keyhandle_idx = 0  # cycle over keyhandles
        while True:
            if not self.is_valid():
                note.update('TIMEOUT. Too slow!')
                raise AskPassword.TimeoutDuringHandling()

            # Cycle over keyhandles. If the wrong key is inserted, u2f-host
            # aborts quickly, so we can try the next keyhandle instead.
            keyhandle = keyhandles[keyhandle_idx]
            keyhandle_idx = (keyhandle_idx + 1) % len(keyhandles)

            # The request is valid for a very short while, so we'll need
            # a timeout on the process.
            timeout = 6  # MUST be lower than openvpn-u2f-verify max $timedelta
            timestamp, request = self._make_challenge_request(keyhandle)
            t1 = time.time()
            try:
                ret = subprocess.run(
                    ['/usr/bin/u2f-host', '-a', 'authenticate', '-o', ORIGIN],
                    input=request.encode('ascii'), stdout=subprocess.PIPE,
                    timeout=timeout)  # short timeout in seconds
            except subprocess.TimeoutExpired:
                pass
            else:
                if ret.returncode == 0:
                    out = ret.stdout.decode('ascii')
                    break

            # FIXME: After 300s (5mins) we abort. At this point you should
            # have your key. If you really want to log in. Restart the
            # OpenVPN client.
            if (time.time() - t0) > 300:
                note.update('TIMEOUT. Too slow!')
                raise AskPassword.TimeoutDuringHandling()

            # Sleep a short while if starting u2f-host failed quickly.
            if (time.time() - t1) < 0.3:
                time.sleep(1)

            # In case the notification was already hidden, re-display it.
            note.show()

        # If you were to feed the 'out' JSON to u2f-server -a authenticate,
        # it should be happy.
        # {"signatureData": "AQAA..",
        #  "clientData": "eyAiY2hhb...",
        #  "keyHandle": "SnVVgZR18w..."}
        # print('JSON:', out)

        # But, because we want minimal data sent over the username and
        # password fields, we'll send only our timestamp and the signature.
        # We'll recreate the JSON found above on the server side.
        jsdec = json.loads(out)
        signature = jsdec['signatureData']
        note.update('PRESSED. Thank you!')
        return keyhandle, timestamp, signature


class AskPasswordHandler(pyinotify.ProcessEvent):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Keep user/pass requests that were done recently by the same process.
        # This way we can match up username and password in the same instance.
        self._reuse_askpassword = {}

    def process_IN_CLOSE_WRITE(self, event):
        self.process_IN_MOVED_TO(event)

    def process_IN_MOVED_TO(self, event):
        """
        event = <Event cookie=688867 dir=False mask=0x80 maskname=IN_MOVED_TO
          name=ask.rCEVu1 path=/run/systemd/ask-password
          pathname=/run/systemd/ask-password/ask.rCEVu1 wd=1 >
        event.pathname = /run/systemd/ask-password/ask.rCEVu1
        """
        self._prune_reuse_askpassword()

        # print(event)
        if os.path.basename(event.pathname).startswith('ask.'):
            self.handle_askfile(event.pathname)

    def handle_askfile(self, pathname):
        try:
            with open(pathname, 'r') as fp:
                data = fp.read()
        except FileNotFoundError:
            print('DEBUG: file is now gone', pathname)
        except Exception as e:
            traceback.print_exc()
            print('ERROR: handle_askfile:', e)
        else:
            try:
                self._handle_askinifile(pathname, data)
            except Exception as e:
                traceback.print_exc()
                print('ERROR: _handle_askinifile:', e)

    def _handle_askinifile(self, filename, inifile):
        """
        [Ask]
        PID=1285316
        Socket=/run/systemd/ask-password/sck.df96c35fda1a42ca
        AcceptCached=0
        Echo=1
        NotAfter=1974186814503
        Message=Enter Auth Username:
        Icon=network-vpn
        """
        lines = inifile.split('\n')
        header = lines[0][1:-1]
        vals = dict(i.split('=', 1) for i in lines[1:] if i)

        process = Process.from_pid(int(vals['PID']))
        if process and process.exe == '/usr/sbin/openvpn' and header == 'Ask':
            assert isinstance(process.pid, int), process.pid
            try:
                ask = self._reuse_askpassword[process.pid]
            except KeyError:
                ask = self._reuse_askpassword[process.pid] = (
                    AskPasswordOpenVpnU2f(process))

            ask.make_request(filename, header, vals)
            ask.handle()
        else:
            # Ignore. This password request is not for us.
            pass

    def _prune_reuse_askpassword(self):
        now = time.time()
        for pid, instance in list(self._reuse_askpassword.items()):
            if (now - instance.last_activity) > 5:
                del self._reuse_askpassword[pid]


"""
From https://systemd.io/PASSWORD_AGENTS/ fetched on 2021-01-29.

> It is easy to write additional agents. The basic algorithm to follow looks
> like this:
>
> - Create an inotify watch on /run/systemd/ask-password, watch for
>   IN_CLOSE_WRITE|IN_MOVED_TO
>
> - Ignore all events on files in that directory that do not start with "ask."
>
> - As soon as a file named "ask.xxxx" shows up, read it. It's a simple .ini
>   file that may be parsed with the usual parsers. The xxxx suffix is
>   randomized.
>
> - Make sure to ignore unknown .ini file keys in those files, so that we can
>   easily extend the format later on.
>
> - You'll find the question to ask the user in the Message= field in the [Ask]
>   section. It is a single-line string in UTF-8, which might be
>   internationalized (by the party that originally asks the question, not by
>   the agent).
>
> - You'll find an icon name (following the XDG icon naming spec) to show next
>   to the message in the Icon= field in the [Ask] section
>
> - You'll find the PID of the client asking the question in the PID= field in
>   the [Ask] section (Before asking your question use kill(PID, 0) and ignore
>   the file if this returns ESRCH; there's no need to show the data of this
>   field but if you want to you may)
>
> - Echo= specifies whether the input should be obscured. If this field is
>   missing or is Echo=0, the input should not be shown.
>
> - The socket to send the response to is configured via Socket= in the [Ask]
>   section. It is a AF_UNIX/SOCK_DGRAM socket in the file system.
>
> - Ignore files where the time specified in the NotAfter= field in the [Ask]
>   section is in the past. The time is specified in usecs, and refers to the
>   CLOCK_MONOTONIC clock. If NotAfter= is 0, no such check should take place.
>
> - Make sure to hide a password query dialog as soon as a) the ask.xxxx file
>   is deleted, watch this with inotify. b) the NotAfter= time elapses, if it
>   is set != 0.
>
> - Access to the socket is restricted to privileged users. To acquire the
>   necessary privileges to send the answer back, consider using PolicyKit. In
>   fact, the GNOME agent we ship does that, and you may simply piggyback on
>   that, by executing "/usr/bin/pkexec /lib/systemd/systemd-reply-password 1
>   /path/to/socket" or "/usr/bin/pkexec /lib/systemd/systemd-reply-password 0
>   /path/to/socket" and writing the password to its standard input. Use ‘1' as
>   argument if a password was entered by the user, or ‘0' if the user canceled
>   the request.
>
> - If you do not want to use PK ensure to acquire the necessary privileges in
>   some other way and send a single datagram to the socket consisting of the
>   password string either prefixed with "+" or with "-" depending on whether
>   the password entry was successful or not. You may but don't have to include
>   a final NUL byte in your message.
"""


def reread_existing(*args, **kwargs):
    print('DEBUG: Re-reading {}'.format(ASK_PASSWORD_DIRECTORY))
    fs = os.listdir(ASK_PASSWORD_DIRECTORY)
    fs = [i for i in fs if i.startswith('ask.')]
    for filename in fs:
        handler.handle_askfile(os.path.join(ASK_PASSWORD_DIRECTORY, filename))


def notifier_run_one(source, condition, notifier):
    notifier.process_events()
    while notifier.check_events():
        notifier.read_events()
        notifier.process_events()
    return True


ASK_PASSWORD_DIRECTORY = '/run/systemd/ask-password'
wm = pyinotify.WatchManager()
handler = AskPasswordHandler()
notifier = pyinotify.Notifier(wm, handler)
mask = pyinotify.IN_CLOSE_WRITE | pyinotify.IN_MOVED_TO
wm.add_watch(ASK_PASSWORD_DIRECTORY, mask)

# Install handler so we re-read files on SIGHUP or SIGUSR1.
signal.signal(signal.SIGHUP, reread_existing)
signal.signal(signal.SIGUSR1, reread_existing)
listen_for_unlock(reread_existing)

# Read/handle already existing files.. just in case.
reread_existing()

# Infinite loop time.
print('Started {}, listening in /run/systemd/ask-password'.format(sys.argv[0]))

if GLib:
    # Set up notifier_run_one() call into GLib MainLoop so we don't have
    # to block in notifier.loop().
    GLib.io_add_watch(notifier._fd, GLib.IO_IN, notifier_run_one, notifier)
    # GLib mainloop.
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    loop = GLib.MainLoop()
    try:
        print('DEBUG: GLib mainloop')
        loop.run()
    except KeyboardInterrupt:
        pass
    notifier.stop()
else:
    # pyinotify mainloop.
    print('DEBUG: pyinotify mainloop')
    notifier.loop()
print('done.')

# vim: set ts=8 sw=4 sts=4 et ai:
